name: Close issues related to a merged pull request based on master branch.

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - hotfix

jobs:
  closeIssueOnPrMergeTrigger:
    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
