on: workflow_dispatch

jobs:
  CreateNewVersion:
    name: CreateNewPackageVersion
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Install Dependencies
        shell: pwsh
        env:
          SFDX_ACCESS_TOKEN: ${{ secrets.SFDX_ACCESS_TOKEN }}
        run: |
          npm i
          npm i -g @salesforce/cli
          sf org login access-token --instance-url  ${{ vars.DEVHUB_INSTANCE_URL }} --no-prompt --alias DevHub --set-default-dev-hub
          sf package version create --package "mkt-connector" --installation-key Accenture -w 30
