name: Test PowerShell on Ubuntu
on: push

jobs:
  QualityChecks:
    name: QualityChecks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        shell: pwsh
        run: |
          npm i
          npm i -g @salesforce/cli
          'y' | sf plugins install @salesforce/sfdx-scanner
          'y' | sf plugins install sfdx-git-delta
      - name: Run Code Scan
        shell: pwsh
        run: |
          mkdir codescan
          sf scanner run -t "src/**/*.cls,src/**/*.trigger" --engine "pmd" -o "codescan/apex-scan.json" -f json -s 3;
          sf scanner run -t "src/**/*.js,!src/**/staticresources/**/*.js" --engine "eslint" --eslintconfig ".eslintrc.json" -o "codescan/eslint-scan.json"  -f json -s 3;
