# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Follows reference pipeline available at docs.dxatscale.io
#
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://docs.dxatscale.io/sfpowerscripts/sfpowerscripts

# This pipeline is used to validate an incoming change using a dev environment fetched from the CI pool

name: "PR Validation - Auto Triggered"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**

  workflow_dispatch:

#Set the environment variables for tracking metrics
env:
  SFPOWERSCRIPTS_NEWRELIC: "true"
  SFPOWERSCRIPTS_NEWRELIC_API_KEY: "${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}"
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  validate:
    name: "Validate Changed Packages"
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

      - name: "Run Scanners"
        run: |
          sf plugins install @salesforce/sfdx-scanner
          mkdir codescan
          sf scanner run -t "src/**/*.cls,src/**/*.trigger" --engine "pmd"-s 3;
          sf scanner run -t "src/**/*.js,!src/**/staticresources/**/*.js" --engine "eslint" --eslintconfig ".eslintrc.json" -s 3;

      - name: "Authenticate Dev Hub"
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url  -f authfile -a devhub

      # Validate source and trigger test
      - name: "Push source to scratch org"
        run: "sfp orchestrator:validate -p ci -v devhub -x"
